name: Deploy to digitalocean
on:
  push:
    branches: [master]

jobs:
  build:
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: Rebuild images
        uses: actions/checkout@master 
        run: |
          docker-compose up -d --build