version: "2"
services:
  nginx-react:
    container_name: weeklyreportui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    environment:
      NODE_ENV: production
    networks:
      - front
    volumes:
      - ./ssl/data/certbot/conf:/etc/letsencrypt
      - ./ssl/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot:v1.17.0
    volumes:
      - ./ssl/data/certbot/conf:/etc/letsencrypt
      - ./ssl/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
networks:
  front:
    external:
      name: french-toast-weekly-report-1-api_front